package br.com.lab.dev.system.timeControl.domain;
// Generated 11/03/2017 10:36:49 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TempoInvestido generated by hbm2java
 */
@Entity
@Table(name = "tempo_investido", catalog = "timeControl")
public class TempoInvestido implements java.io.Serializable {

	private Integer idTempoInvestido;
	private int diaIdDia;
	private int atividadeIdAtividade;
	private Date horasGastas;
	private Date dataInicio;
	private Date dataFim;

	public TempoInvestido() {
	}

	public TempoInvestido(int diaIdDia, int atividadeIdAtividade, Date horasGastas, Date dataInicio, Date dataFim) {
		this.diaIdDia = diaIdDia;
		this.atividadeIdAtividade = atividadeIdAtividade;
		this.horasGastas = horasGastas;
		this.dataInicio = dataInicio;
		this.dataFim = dataFim;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tempo_investido", unique = true, nullable = false)
	public Integer getIdTempoInvestido() {
		return this.idTempoInvestido;
	}

	public void setIdTempoInvestido(Integer idTempoInvestido) {
		this.idTempoInvestido = idTempoInvestido;
	}

	@Column(name = "dia_id_dia", nullable = false)
	public int getDiaIdDia() {
		return this.diaIdDia;
	}

	public void setDiaIdDia(int diaIdDia) {
		this.diaIdDia = diaIdDia;
	}

	@Column(name = "atividade_id_atividade", nullable = false)
	public int getAtividadeIdAtividade() {
		return this.atividadeIdAtividade;
	}

	public void setAtividadeIdAtividade(int atividadeIdAtividade) {
		this.atividadeIdAtividade = atividadeIdAtividade;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horas_gastas", nullable = false, length = 8)
	public Date getHorasGastas() {
		return this.horasGastas;
	}

	public void setHorasGastas(Date horasGastas) {
		this.horasGastas = horasGastas;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_inicio", nullable = false, length = 19)
	public Date getDataInicio() {
		return this.dataInicio;
	}

	public void setDataInicio(Date dataInicio) {
		this.dataInicio = dataInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_fim", nullable = false, length = 19)
	public Date getDataFim() {
		return this.dataFim;
	}

	public void setDataFim(Date dataFim) {
		this.dataFim = dataFim;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idTempoInvestido == null) ? 0 : idTempoInvestido.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TempoInvestido other = (TempoInvestido) obj;
		if (idTempoInvestido == null) {
			if (other.getIdTempoInvestido() != null)
				return false;
		} else if (!idTempoInvestido.equals(other.getIdTempoInvestido()))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "TempoInvestido [idTempoInvestido=" + idTempoInvestido + ", diaIdDia=" + diaIdDia
				+ ", atividadeIdAtividade=" + atividadeIdAtividade + ", horasGastas=" + horasGastas + ", dataInicio="
				+ dataInicio + ", dataFim=" + dataFim + "]";
	}
}