package teste;
// Generated 11/03/2017 10:33:18 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Atividade generated by hbm2java
 */
@Entity
@Table(name = "atividade", catalog = "timeControl")
public class Atividade implements java.io.Serializable {

	private Integer idAtividade;
	private int usuarioIdUsuario;
	private String nome;
	private String descricao;
	private int prioridade;
	private String categoria;

	public Atividade() {
	}

	public Atividade(int usuarioIdUsuario, String nome, String descricao, int prioridade) {
		this.usuarioIdUsuario = usuarioIdUsuario;
		this.nome = nome;
		this.descricao = descricao;
		this.prioridade = prioridade;
	}

	public Atividade(int usuarioIdUsuario, String nome, String descricao, int prioridade, String categoria) {
		this.usuarioIdUsuario = usuarioIdUsuario;
		this.nome = nome;
		this.descricao = descricao;
		this.prioridade = prioridade;
		this.categoria = categoria;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_atividade", unique = true, nullable = false)
	public Integer getIdAtividade() {
		return this.idAtividade;
	}

	public void setIdAtividade(Integer idAtividade) {
		this.idAtividade = idAtividade;
	}

	@Column(name = "usuario_id_usuario", nullable = false)
	public int getUsuarioIdUsuario() {
		return this.usuarioIdUsuario;
	}

	public void setUsuarioIdUsuario(int usuarioIdUsuario) {
		this.usuarioIdUsuario = usuarioIdUsuario;
	}

	@Column(name = "nome", nullable = false, length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "descricao", nullable = false)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "prioridade", nullable = false)
	public int getPrioridade() {
		return this.prioridade;
	}

	public void setPrioridade(int prioridade) {
		this.prioridade = prioridade;
	}

	@Column(name = "categoria", length = 50)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

}
