package br.com.lab.dev.system.timeControl.modelo;
// Generated Mar 8, 2017 12:14:54 AM by Hibernate Tools 4.3.1.Final

/**
 * Atividade generated by hbm2java
 */
public class Atividade implements java.io.Serializable {

	private Integer idAtividade;
	private int usuarioIdUsuario;
	private String nome;
	private String descricao;
	private int prioridade;
	private String categoria;

	public Atividade() {
	}

	public Atividade(int usuarioIdUsuario, String nome, String descricao, int prioridade) {
		this.usuarioIdUsuario = usuarioIdUsuario;
		this.nome = nome;
		this.descricao = descricao;
		this.prioridade = prioridade;
	}

	public Atividade(int usuarioIdUsuario, String nome, String descricao, int prioridade, String categoria) {
		this.usuarioIdUsuario = usuarioIdUsuario;
		this.nome = nome;
		this.descricao = descricao;
		this.prioridade = prioridade;
		this.categoria = categoria;
	}

	public Integer getIdAtividade() {
		return this.idAtividade;
	}

	public void setIdAtividade(Integer idAtividade) {
		this.idAtividade = idAtividade;
	}

	public int getUsuarioIdUsuario() {
		return this.usuarioIdUsuario;
	}

	public void setUsuarioIdUsuario(int usuarioIdUsuario) {
		this.usuarioIdUsuario = usuarioIdUsuario;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public int getPrioridade() {
		return this.prioridade;
	}

	public void setPrioridade(int prioridade) {
		this.prioridade = prioridade;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

}
