package br.com.lab.dev.system.timeControl.modelo;
// Generated Mar 8, 2017 12:14:54 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Dia generated by hbm2java
 */
public class Dia implements java.io.Serializable {

	private Integer idDia;
	private Date data2;
	private Date totalHorasDia;

	public Dia() {
	}

	public Dia(Date data2, Date totalHorasDia) {
		this.data2 = data2;
		this.totalHorasDia = totalHorasDia;
	}

	public Integer getIdDia() {
		return this.idDia;
	}

	public void setIdDia(Integer idDia) {
		this.idDia = idDia;
	}

	public Date getData2() {
		return this.data2;
	}

	public void setData2(Date data2) {
		this.data2 = data2;
	}

	public Date getTotalHorasDia() {
		return this.totalHorasDia;
	}

	public void setTotalHorasDia(Date totalHorasDia) {
		this.totalHorasDia = totalHorasDia;
	}

}
