package br.com.lab.dev.system.timeControl.modelo;
// Generated Mar 9, 2017 12:01:10 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TempoInvestido generated by hbm2java
 */
@Entity
@Table(name = "tempo_investido", catalog = "timeControl")
public class TempoInvestido implements java.io.Serializable {

	private Integer idTempoInvestido;
	private int atividadeIdAtividade;
	private int diaIdDia;
	private Date totalHoras;
	private Date dataInicio;
	private Date dataFim;

	public TempoInvestido() {
	}

	public TempoInvestido(int atividadeIdAtividade, int diaIdDia, Date totalHoras, Date dataInicio, Date dataFim) {
		this.atividadeIdAtividade = atividadeIdAtividade;
		this.diaIdDia = diaIdDia;
		this.totalHoras = totalHoras;
		this.dataInicio = dataInicio;
		this.dataFim = dataFim;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tempo_investido", unique = true, nullable = false)
	public Integer getIdTempoInvestido() {
		return this.idTempoInvestido;
	}

	public void setIdTempoInvestido(Integer idTempoInvestido) {
		this.idTempoInvestido = idTempoInvestido;
	}

	@Column(name = "atividade_id_atividade", nullable = false)
	public int getAtividadeIdAtividade() {
		return this.atividadeIdAtividade;
	}

	public void setAtividadeIdAtividade(int atividadeIdAtividade) {
		this.atividadeIdAtividade = atividadeIdAtividade;
	}

	@Column(name = "dia_id_dia", nullable = false)
	public int getDiaIdDia() {
		return this.diaIdDia;
	}

	public void setDiaIdDia(int diaIdDia) {
		this.diaIdDia = diaIdDia;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "total_horas", nullable = false, length = 8)
	public Date getTotalHoras() {
		return this.totalHoras;
	}

	public void setTotalHoras(Date totalHoras) {
		this.totalHoras = totalHoras;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_inicio", nullable = false, length = 19)
	public Date getDataInicio() {
		return this.dataInicio;
	}

	public void setDataInicio(Date dataInicio) {
		this.dataInicio = dataInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_fim", nullable = false, length = 19)
	public Date getDataFim() {
		return this.dataFim;
	}

	public void setDataFim(Date dataFim) {
		this.dataFim = dataFim;
	}

}
