package br.com.lab.dev.system.timeControl.modelo;
// Generated Mar 8, 2017 12:14:54 AM by Hibernate Tools 4.3.1.Final

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer idUsuario;
	private String nome;
	private String email;
	private String senha;
	private String profissao;

	public Usuario() {
	}

	public Usuario(String nome, String email, String senha, String profissao) {
		this.nome = nome;
		this.email = email;
		this.senha = senha;
		this.profissao = profissao;
	}

	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	public String getProfissao() {
		return this.profissao;
	}

	public void setProfissao(String profissao) {
		this.profissao = profissao;
	}

}
